### ISSUE TITLE
乱码问题

### ISSUE THREAD

**Issue by junyi666-666** [MeanZhang/OptimizedAES#1]
你好，我运行测试代码，得到的解密文件是乱码的，我该怎么解决？

**Comment by MeanZhang** [comment]
你好，测试文件只是用来测试速度的，内容是我随机生成的，本来就是乱码。
你可以修改测试文件的内容，另外测试，测试完成后明文文件和测试前应该是一样的。

**Comment by junyi666-666** [comment]
> 你好，测试文件只是用来测试速度的，内容是我随机生成的，本来就是乱码。 你可以修改测试文件的内容，另外测试，测试完成后明文文件和测试前应该是一样的。

**Comment by junyi666-666** [comment]
你好，我修改文件内容之后再次测试，还是乱码的形式

**Comment by MeanZhang** [comment]
> 你好，我修改文件内容之后再次测试，还是乱码的形式

我自己测试是没问题的。
![image](https://user-images.githubusercontent.com/40561709/168095952-33024eb8-48d1-42bb-b12c-01a44b54c76d.png)
